name: improveEdit3d
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - _pytorch_select=0.2=gpu_0
  - alsa-lib=1.2.8=h166bdaf_0
  - attr=2.5.1=h166bdaf_1
  - blas=1.0=mkl
  - brotlipy=0.7.0=py310h5764c6d_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2023.5.7=hbcca054_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h255011f_3
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - cli11=2.3.2=hcb278e6_0
  - cmake=3.26.3=h077f3f9_0
  - cryptography=40.0.2=py310h34c0648_0
  - cudatoolkit=11.8.0=h37601d7_11
  - cython=0.29.34=py310heca2aa9_0
  - dbus=1.13.6=h5008d03_3
  - expat=2.5.0=hcb278e6_1
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_hc118613_107
  - filelock=3.12.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=hca18f0e_1
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - glib=2.76.2=hfc55251_0
  - glib-tools=2.76.2=hfc55251_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py310h3ec546c_1
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.22.0=h4243ec0_2
  - gstreamer=1.22.0=h25f0c4b_2
  - gstreamer-orc=0.4.33=h166bdaf_0
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf5=1.14.0=nompi_hb72d44e_103
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jack=1.9.22=h11f4161_0
  - jasper=4.0.0=h0ff4b12_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.0.6=hcb278e6_1
  - libblas=3.9.0=12_linux64_mkl
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=15.0.7=default_had23c3d_1
  - libclang13=15.0.7=default_h3e3d535_1
  - libcups=2.3.3=h36d4200_3
  - libcurl=8.0.1=h588be90_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h28343ad_4
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.2=h27087fc_0
  - libgcc-ng=12.2.0=h65d4601_19
  - libgcrypt=1.10.1=h166bdaf_0
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.76.2=hebfc3b9_0
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=12.2.0=h65d4601_19
  - libgpg-error=1.46=h620e276_0
  - libhwloc=2.9.1=hd6dc26d_0
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h166bdaf_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm15=15.0.7=hadd5161_1
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=15.3=hbcd7760_0
  - libsndfile=1.2.0=hb75c966_0
  - libsqlite=3.41.2=h2797004_1
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libsystemd0=253=h8c4010b_1
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.5.0=h6adf6a1_2
  - libtool=2.4.7=h27087fc_0
  - libudev1=253=h0b41bf4_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.44.2=h166bdaf_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.13.0=hcb278e6_0
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=16.0.3=h4dfa4b3_0
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=2.1.2=py310h1fa729e_0
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py310ha2c4b55_0
  - mkl_fft=1.3.1=py310h2b4bcf5_1
  - mkl_random=1.2.2=py310h00e6091_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.0=hb012696_0
  - mpg123=1.31.3=hcb278e6_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - mysql-common=8.0.32=hf1915f5_2
  - mysql-libs=8.0.32=hca2cd23_2
  - nanoflann=1.4.2=ha770c72_0
  - ncurses=6.3=h27087fc_1
  - nettle=3.6=he412f7d_0
  - networkx=3.1=pyhd8ed1ab_0
  - ninja=1.11.1=h924138e_0
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - numpy=1.24.3=py310hd5efca6_0
  - numpy-base=1.24.3=py310h8e6c178_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.0=hd590300_3
  - packaging=23.1=pyhd8ed1ab_0
  - pangolin=0.8
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.40=hc3806b6_0
  - pillow=9.4.0=py310h023d228_1
  - pip=23.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=3.5.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio=16.1=hcb278e6_3
  - pulseaudio-client=16.1=h5195f5e_3
  - pulseaudio-daemon=16.1=ha8d29e2_3
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.11=he550d4f_0_cpython
  - python_abi=3.10=3_cp310
  - pytorch=2.0.1=py3.10_cpu_0
  - pytorch-mutex=1.0=cpu
  - qt=5.15.8=hf11cfaa_0
  - qt-main=5.15.8=h5d23da1_6
  - qt-webengine=5.15.8=h77d6d84_0
  - readline=8.2=h8228510_1
  - rhash=1.4.3=h166bdaf_0
  - scikit-learn=1.2.2=py310h41b6a48_1
  - scipy=1.10.1=py310h8deb116_2
  - setuptools=67.7.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h2c6b66d_1
  - tbb=2021.9.0=hf52228f_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h27826a3_0
  - torchaudio=2.0.2=py310_cpu
  - torchvision=0.15.2=py310_cpu
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
  - pip:
      - absl-py==1.4.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.6.2
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arm-pyart==1.15.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-generator==1.10
      - attrs==23.1.0
      - awscli==1.27.133
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - black==23.3.0
      - bleach==6.0.0
      - boto3==1.26.133
      - botocore==1.29.133
      - cached-property==1.5.2
      - cachetools==5.3.0
      - cftime==1.6.2
      - chardet==5.1.0
      - click==8.1.3
      - clip==0.2.0
      - cloudpickle==2.2.1
      - colorama==0.4.4
      - comm==0.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - dask==2023.4.1
      - dataclasses==0.6
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docutils==0.16
      - edit3d==0.0.1
      - entrypoints==0.4
      - ephem==4.1.4
      - executing==1.2.0
      - fastjsonschema==2.16.3
      - fonttools==4.39.4
      - fqdn==1.5.1
      - fsspec==2023.5.0
      - future==0.18.3
      - fvcore==0.1.5.post20221221
      - gdown==4.7.1
      - geographiclib==2.0
      - geopy==2.3.0
      - google-auth==2.18.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.54.0
      - h5netcdf==1.1.0
      - h5py==3.8.0
      - hydra-core==1.3.2
      - imageio==2.28.1
      - imageio-ffmpeg==0.4.8
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - iopath==0.1.10
      - ipykernel==6.23.0
      - ipython==8.13.2
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - isoduration==20.11.0
      - jedi==0.18.2
      - jmespath==1.0.1
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.2.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-server==2.5.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.7
      - kiwisolver==1.4.4
      - lat-lon-parser==1.3.0
      - lazy-loader==0.2
      - lmdb==1.4.1
      - locket==1.0.0
      - lpips==0.1.4
      - markdown==3.4.3
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mistune==2.0.5
      - more-itertools==9.1.0
      - mypy-extensions==1.0.0
      - nbclassic==1.0.0
      - nbclient==0.7.4
      - nbconvert==7.4.0
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - netcdf4==1.6.3
      - netcdftime==1.0.0a2
      - nose==1.3.7
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - open-radar-data==0.0.4
      - opencv-python==4.7.0.72
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - partd==1.4.0
      - pathspec==0.11.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - plyfile==0.9
      - portalocker==2.7.0
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.38
      - protobuf==3.20.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.6
      - pydot==1.4.2
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyproj==3.5.0
      - pyrsistent==0.19.3
      - pyspng==0.1.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==5.4.1
      - pyzmq==25.0.2
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - regex==2023.5.5
      - requests==2.30.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rsa==4.7.2
      - s3fs==0.4.2
      - s3transfer==0.6.1
      - scikit-image==0.20.0
      - send2trash==1.8.2
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6
      - termcolor==2.3.0
      - terminado==0.17.1
      - testpath==0.6.0
      - tifffile==2023.4.12
      - tinycss2==1.2.1
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.0
      - tornado==6.3.1
      - tqdm==4.65.0
      - traitlets==5.9.0
      - trimesh==3.21.6
      - typed-ast==1.5.4
      - uri-template==1.2.0
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - werkzeug==2.3.4
      - widgetsnbextension==4.0.7
      - xarray==2023.4.2
      - xarray-datatree==0.0.12
      - xmltodict==0.13.0
      - xradar==0.2.0
      - yacs==0.1.8
      - zipp==3.15.0
prefix: /home/user/miniconda3/envs/improveEdit3d
